workflows:
  ios-workflow:
    name: SiteNative iOS without OneSignal
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: 846c21ba-7a70-48b8-bc87-ac157ac3643f
        APP_STORE_CONNECT_KEY_IDENTIFIER: WHM4WT35P2
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbxydrAQU+kWwTuaB
         uWpCyZ1BauZU9WmYhVZy1rfEfk6gCgYIKoZIzj0DAQehRANCAARTXaOHyBOr/VgX
         zsMgEkPOHAE4YqQXk3IxiIRIaq1kLhnquUrcSy/ByKm6vZttoPRGP9pmyXxtLzBo
         2L5Wo/R3
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         -----BEGIN RSA PRIVATE KEY-----
         MIIEowIBAAKCAQEAx8dCxfsh4uywLEpUPKWMdJLxjlVtckpumLxJkQS/NkSzQI+s
         61vw0V3cvCul3DyE6ztjoABt0jiVwjfooogtVuGzicXEYV4StbGMeD5CxNrUA+TO
         S7STkzaSuS/CZcJPTx+bCLMwtGQ94KbNeZIZqvNCokWgnkGSYMg0TPsb56uiV+qP
         TE9VlMB27cBmvt8OHWPbgDsp6slKNUQp0hMl5eCtuceBmfElIr0i81EJHKVAJ0eT
         DI6ya5+8XQIkF290UGeRnAnHc7+MCx+ivd5FIVSoDMSaafK7YQEVFtLYN6520R0b
         LGNJCSX1JY5ZZxKgo4zX7LeiuuitKRyJu/kMbwIDAQABAoIBAE02DO+ZlMowchJc
         E9xwmy0+0Y8SIz+l1sK/GquqqwAdYy4TmWBJY3R3k2VCdVL+LN0BUgq3v7oc1nx+
         wTF38hX/GzWnMrPy+MYyPbkHTyTn8kMi/jwyKUsfL2vVMovDooVREMk3AB7oEyYt
         MYLH3ZW9eMZgpKglbZ5sIhKShoFtnF80SNd5/NZj2q2w8WayimmjIr3At2wXJE+f
         0Wnb/yMZPii7AWfQJx7jZaXli+zDwi4alI3is29ET70O7qzvU7CYau9CJ7stapMF
         vNkhPGQC93jAYJng58PSDOxlNFI9KadOk31USs9vUSa8a4jv8F8QbhfYk1WfgI1w
         ulloA3kCgYEA6orNRgwrGOe8hrb5xRvo8AFhu+t5it/9SmaX51Op83R6pcdJNVmx
         7Vl2OFw8zY2LWQPB+VsDbxetC5hVFMnvKcdc0Y9L2pmVD3oFh276A5bd1XXCOPYi
         sll7wy+kVwaZX/LL67/I5DI+/6ery9fW69vbsDutsdmQ5kDVy+32Mw0CgYEA2g5B
         5z7W574zTIvCYrGgkif1lj0At6otreR7g2oNIerFA5I4+5QrdZw8Ks6YQxh9HRnz
         9koBYVNnoNsq2qWLCebiYzr9ltk0TZCahG6tYUENr08pBCHHd9hfn5nh0M9ktprM
         033y621K/fX7B4RX3HMwgGXYnfNLZ3zgaQajDmsCgYBvcWyAMB/6QYJO8HpVsiFI
         iR+LTyP9XNjZlU3wWMyUJXBxfPPIKcplYPDPbuRlNzBTJ3nvpdNH4hQTQlqK+jht
         vZDY8iG0yO0O4YfnBlA9jF3zo3SZ5DowTFyGLgkEYNpXwOIsLoCiDU3p5B25SeGR
         SHJmlrS9oQc8oOn1cChfsQKBgGTPsKJTiBGt+pOKDb2JN546wSzLWTiQgfviJURV
         VGr42krTYGrXTtxZ9esohnaGrNk2dXbJMign4kIY8ZASdtyGFOYhkLocAzVVBErz
         zE6pP8VsCJ9zan+61kK4ZxEdwQc3PDkPAq7bYY9WGM+Z3PD7hFHoRCSKJbNbpXiI
         6/uvAoGBAMWN1WyehiK9TOupCMtk6+BKTo8Rr8ztraJ5TF4XvvJdpvMRN26Q5B7/
         PVTX36bFQfLoESRIDRoBprp6gEJPSYjXpOS1fJlQFi7FwnCAPhenw31rv06cdx4B
         qVfAWlh7/6FfibEmpomFaMaEyNAcJ1zEfcPqvAB1eCFT6/eK8Hw+
         -----END RSA PRIVATE KEY-----
         

        BUNDLE_ID: "app.cruzeirocolorico.com"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://gamedevs.ml/backend/api/observe/notice/b5f9dde9-9855-8a66-6772-dd842d4c6f0d