workflows:
  ios-workflow:
    name: SiteNative iOS without OneSignal
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: 846c21ba-7a70-48b8-bc87-ac157ac3643f
        APP_STORE_CONNECT_KEY_IDENTIFIER: Q6M5G97MV4
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTqowByP1S2SByMgM
         2SJVCkTwL4LsESL8zmE2VdYv2CGgCgYIKoZIzj0DAQehRANCAARcY2wix0Qwdd1m
         AKd03UZgBUHYtPRI9VxvCINQ0qAk0M7WyeKQ6+JKDPr/ttJNXYYJUGgB2F6ZJZZk
         OlI5kSfI
         -----END PRIVATE KEY-----

        BUNDLE_ID: "com.cruzeirocolorido.app"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=2.0.3 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://gamedevs.ml/backend/api/observe/notice/b5f9dde9-9855-8a66-6772-dd842d4c6f0d
